In [1]:
if 0 :
    %matplotlib inline
else :
    %matplotlib notebook

#  Import  libraries

In [2]:
import sys
import os
module_path = os.path.abspath('.') +"\\_scripts"
print(module_path)

if module_path not in sys.path:
    sys.path.append(module_path)
from _00_Import_packages_git3 import *

C:\Users\ng947ac\Documents\Daniel\jupyter\SoSTrades\jupyter_doc\_scripts
C:\Users\ng947ac\Documents\Daniel\git\workspace
C:\Users\ng947ac\Documents\Daniel\git\workspace\sosgemseo\src\
C:\Users\ng947ac\Documents\Daniel\git\workspace\sostrades-core


In [3]:
#from sos_trades_core import *

In [4]:
from platform import python_version

print(python_version())

3.9.7


In [5]:
import numpy
print(numpy.__version__)

1.20.3


In [6]:
import scipy
print(scipy.__version__)

1.7.1


In [7]:
import pandas
print(pandas.__version__)

1.3.0


In [8]:
from numpy import array
import pandas as pd
from sos_trades_core.execution_engine.execution_engine import ExecutionEngine
from numpy.testing import assert_array_equal, assert_array_almost_equal  # @UnresolvedImport
import os
from gemseo.core.mdo_scenario import MDOScenario

 # 0) Set the  discipline : here SobieskiMission

In [9]:
#from sos_trades_core.sos_wrapping.test_discs.sellar import Sellar1
from sos_trades_core.execution_engine.execution_engine import ExecutionEngine

In [10]:
ns_test = 'MyStudy'
ee = ExecutionEngine(ns_test)
ns_dict = {'ns_OptimSobieski': ns_test} # conform to shared variable x
ee.ns_manager.add_ns_def(ns_dict)

In [11]:
# Choice of the discipline (File that provides the wrapper and associated wrapper)
mod_path0 = 'sos_trades_core.sos_wrapping.test_discs.sos_Sobieski.SobieskiMission'

In [12]:
disc_name = 'SobieskiMission'
disc0_builder = ee.factory.get_builder_from_module(disc_name, mod_path0)
ee.factory.set_builders_to_coupling_builder(disc0_builder)

ee.configure() 

INFO:SoS.EE:configuring ...
INFO:SoS.EE.Coupling:The MDA solver of the Coupling MyStudy is set to MDAJacobi


# Display study structure

In [13]:
ee.display_treeview_nodes()

INFO:SoS.EE:Nodes representation for Treeview MyStudy
|_ MyStudy
	|_ SobieskiMission


'Nodes representation for Treeview MyStudy\n|_ MyStudy\n\t|_ SobieskiMission'

In [14]:
ee.display_treeview_nodes(True)

INFO:SoS.EE:Nodes representation for Treeview MyStudy
|_ MyStudy
	-> acceleration
	-> authorize_self_coupled_disciplines
	-> cache_file_path
	-> cache_type
	-> chain_linearize
	-> debug_mode
	-> epsilon0
	-> group_mda_disciplines
	-> linear_solver_MDA
	-> linear_solver_MDA_options
	-> linear_solver_MDA_preconditioner
	-> linear_solver_MDO
	-> linear_solver_MDO_options
	-> linear_solver_MDO_preconditioner
	-> linearization_mode
	-> max_mda_iter
	-> n_processes
	-> n_subcouplings_parallel
	-> relax_factor
	-> sub_mda_class
	-> tolerance
	-> tolerance_gs
	-> use_lu_fact
	-> warm_start
	-> warm_start_threshold
	-> y_14
	-> y_24
	-> y_34
	-> z
	<- residuals_history
	<- y_4
	|_ SobieskiMission
		-> cache_file_path
		-> cache_type
		-> debug_mode
		-> linearization_mode


'Nodes representation for Treeview MyStudy\n|_ MyStudy\n\t-> acceleration\n\t-> authorize_self_coupled_disciplines\n\t-> cache_file_path\n\t-> cache_type\n\t-> chain_linearize\n\t-> debug_mode\n\t-> epsilon0\n\t-> group_mda_disciplines\n\t-> linear_solver_MDA\n\t-> linear_solver_MDA_options\n\t-> linear_solver_MDA_preconditioner\n\t-> linear_solver_MDO\n\t-> linear_solver_MDO_options\n\t-> linear_solver_MDO_preconditioner\n\t-> linearization_mode\n\t-> max_mda_iter\n\t-> n_processes\n\t-> n_subcouplings_parallel\n\t-> relax_factor\n\t-> sub_mda_class\n\t-> tolerance\n\t-> tolerance_gs\n\t-> use_lu_fact\n\t-> warm_start\n\t-> warm_start_threshold\n\t-> y_14\n\t-> y_24\n\t-> y_34\n\t-> z\n\t<- residuals_history\n\t<- y_4\n\t|_ SobieskiMission\n\t\t-> cache_file_path\n\t\t-> cache_type\n\t\t-> debug_mode\n\t\t-> linearization_mode'

# Display discipline structure

In [15]:
my_disc0 = ee.root_process.sos_disciplines[0]

In [16]:
DESC_IN = my_disc0.DESC_IN
DESC_OUT = my_disc0.DESC_OUT
DESC_IN_df = pd.DataFrame.from_dict(DESC_IN,orient='index')
DESC_OUT_df = pd.DataFrame.from_dict(DESC_OUT,orient='index')

In [17]:
DESC_IN_df

type                                  default visibility  \
y_14  array          [50606.97417114, 7306.20262124]     Shared   
y_24  array                             [4.15006276]     Shared   
y_34  array                             [1.10754577]     Shared   
z     array  [0.05, 45000.0, 1.6, 5.5, 55.0, 1000.0]     Shared   

             namespace  
y_14  ns_OptimSobieski  
y_24  ns_OptimSobieski  
y_34  ns_OptimSobieski  
z     ns_OptimSobieski

In [18]:
DESC_OUT_df

type visibility         namespace
y_4  array     Shared  ns_OptimSobieski

# Provide inputs

In [19]:
import numpy as np

In [20]:
priv_in_values = {
                  'MyStudy.y_14': [50606.9,7306.20],
                  'MyStudy.y_24':  [4.15], 
                  'MyStudy.y_34': [1.10], 
                  'MyStudy.z': [0.05,45000,1.6,5.5,55,1000],
                  }

In [21]:
priv_in_values

{'MyStudy.y_14': [50606.9, 7306.2],
 'MyStudy.y_24': [4.15],
 'MyStudy.y_34': [1.1],
 'MyStudy.z': [0.05, 45000, 1.6, 5.5, 55, 1000]}

In [22]:
ee.dm.set_values_from_dict(priv_in_values)
ee.root_process.update_from_dm()

# Execute

In [23]:
print(ee.execute())

INFO:SoS.EE:PROCESS EXECUTION MyStudy STARTS...
INFO:SoS.EE:PROCESS EXECUTION MyStudy ENDS.


{'MyStudy.y_14': [50606.9, 7306.2], 'MyStudy.y_24': [4.15], 'MyStudy.y_34': [1.1], 'MyStudy.z': [0.05, 45000, 1.6, 5.5, 55, 1000], 'MyStudy.y_4': array([539.45633495])}


# Display Results

In [24]:
my_disc0.get_data_io_dict('out')['y_4']['value']

array([539.45633495])

In [25]:
my_disc0.compute_sos_jacobian()

In [26]:
#my_disc0.jac

In [27]:
pd.DataFrame(my_disc0.jac)

y_4
y_14    [[-0.01153569594573601, 0.07990279641349372]]
y_24                           [[129.98947830112547]]
y_34                          [[-490.41484995424616]]
z     [[0.0, 0.0, 337.16020934354424, 0.0, 0.0, 0.0]]

# 1) Set the discipline : here SobieskiStructure

In [28]:
ns_test = 'MyStudy'
ee = ExecutionEngine(ns_test)
ns_dict = {'ns_OptimSobieski': ns_test} # conform to shared variable x
ee.ns_manager.add_ns_def(ns_dict)

In [29]:
# Choice of the discipline (File that provides the wrapper and associated wrapper)
mod_path1 = 'sos_trades_core.sos_wrapping.test_discs.sos_Sobieski.SobieskiStructure'

In [30]:
disc_name = 'SobieskiStructure'
disc1_builder = ee.factory.get_builder_from_module(disc_name, mod_path1)
ee.factory.set_builders_to_coupling_builder(disc1_builder)

ee.configure() 

INFO:SoS.EE:configuring ...
INFO:SoS.EE.Coupling:The MDA solver of the Coupling MyStudy is set to MDAJacobi


In [31]:
ee.display_treeview_nodes()

INFO:SoS.EE:Nodes representation for Treeview MyStudy
|_ MyStudy
	|_ SobieskiStructure


'Nodes representation for Treeview MyStudy\n|_ MyStudy\n\t|_ SobieskiStructure'

In [32]:
my_disc1 = ee.root_process.sos_disciplines[0]

In [33]:
DESC_IN = my_disc1.DESC_IN
DESC_OUT = my_disc1.DESC_OUT
DESC_IN_df = pd.DataFrame.from_dict(DESC_IN,orient='index')
DESC_OUT_df = pd.DataFrame.from_dict(DESC_OUT,orient='index')

In [34]:
DESC_IN_df

type                                  default visibility  \
x_1   array                              [0.25, 1.0]     Shared   
y_21  array                          [50606.9741711]     Shared   
y_31  array                          [6354.32430691]     Shared   
z     array  [0.05, 45000.0, 1.6, 5.5, 55.0, 1000.0]     Shared   

             namespace  
x_1   ns_OptimSobieski  
y_21  ns_OptimSobieski  
y_31  ns_OptimSobieski  
z     ns_OptimSobieski

In [35]:
DESC_OUT_df

type visibility         namespace
y_1   array     Shared  ns_OptimSobieski
y_11  array     Shared  ns_OptimSobieski
y_14  array     Shared  ns_OptimSobieski
g_1   array     Shared  ns_OptimSobieski
y_12  array     Shared  ns_OptimSobieski

#Provide inputs

In [36]:
priv_in_values = {
                  'MyStudy.x_1': [0.25,1.0],
                  'MyStudy.y_21':  [50606.9], 
                  'MyStudy.y_31': [6354.32], 
                  'MyStudy.z': [0.05,45000,1.6,5.5,55,1000]
                  }

In [37]:
priv_in_values

{'MyStudy.x_1': [0.25, 1.0],
 'MyStudy.y_21': [50606.9],
 'MyStudy.y_31': [6354.32],
 'MyStudy.z': [0.05, 45000, 1.6, 5.5, 55, 1000]}

In [38]:
ee.dm.set_values_from_dict(priv_in_values)
ee.root_process.update_from_dm()

In [39]:
print(ee.execute())

INFO:SoS.EE:PROCESS EXECUTION MyStudy STARTS...
INFO:SoS.EE:PROCESS EXECUTION MyStudy ENDS.


{'MyStudy.x_1': [0.25, 1.0], 'MyStudy.y_21': [50606.9], 'MyStudy.y_31': [6354.32], 'MyStudy.z': [0.05, 45000, 1.6, 5.5, 55, 1000], 'MyStudy.y_1': array([5.06069601e+04, 7.30620262e+03, 9.50000000e-01]), 'MyStudy.y_11': array([0.15591899]), 'MyStudy.y_12': array([5.06069601e+04, 9.50000000e-01]), 'MyStudy.y_14': array([50606.96011166,  7306.20262124]), 'MyStudy.g_1': array([ 0.035     , -0.00666667, -0.0275    , -0.04      , -0.04833333,
       -0.09      , -0.15      ])}


In [40]:
my_disc1.get_data_io_dict('out')['y_1']['value']

array([5.06069601e+04, 7.30620262e+03, 9.50000000e-01])

In [41]:
my_disc1.get_data_io_dict('out')['y_11']['value']

array([0.15591899])

In [42]:
my_disc1.get_data_io_dict('out')['y_14']['value']

array([50606.96011166,  7306.20262124])

In [43]:
my_disc1.get_data_io_dict('out')['g_1']['value']

array([ 0.035     , -0.00666667, -0.0275    , -0.04      , -0.04833333,
       -0.09      , -0.15      ])

In [44]:
my_disc1.get_data_io_dict('out')['y_12']['value']

array([5.06069601e+04, 9.50000000e-01])

In [45]:
my_disc1.compute_sos_jacobian()

In [46]:
#my_disc1.jac

In [47]:
 pd.DataFrame(my_disc1.jac)

y_1  \
z     [[10552.552501360551, 0.0, 0.0, 603.6577153806...   
x_1   [[955.7149992340906, 74665.23431516337], [0.0,...   
y_21             [[0.13148732054655302], [0.0], [-0.0]]   
y_31                              [[1.0], [0.0], [0.0]]   

                                                    g_1  \
z     [[-19.962499999999995, 0.0, 0.0, 0.04545454545...   
x_1   [[0.2666666666666669, -0.7500000000000001], [0...   
y_21  [[0.0], [0.0], [0.0], [0.0], [0.0], [-0.0], [0...   
y_31  [[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [-0...   

                                                   y_12  \
z     [[10552.552501360551, 0.0, 0.0, 603.6577153806...   
x_1   [[955.7149992340906, 74665.23431516337], [-0.1...   
y_21                    [[0.13148732054655302], [-0.0]]   
y_31                                     [[1.0], [0.0]]   

                                                   y_14  \
z     [[10552.552501360551, 0.0, 0.0, 603.6577153806...   
x_1   [[955.7149992340906, 74665.23431516337], [0.0,...   
y_21                     [[0.13148732054655302], [0.0]]   
y_31                                     [[1.0], [0.0]]   

                                                   y_11  
z     [[2.415675167797657, 0.0, 0.0, -0.013152957544...  
x_1     [[-0.003186503279217559, -0.24894556868887197]]  
y_21                         [[-4.383992910364444e-07]]  
y_31                         [[-3.334156397850009e-06]]

# 2) Set the discipline : here SobieskiAerodynamics

In [48]:
ns_test = 'MyStudy'
ee = ExecutionEngine(ns_test)
ns_dict = {'ns_OptimSobieski': ns_test} # conform to shared variable x
ee.ns_manager.add_ns_def(ns_dict)

In [49]:
# Choice of the discipline (File that provides the wrapper and associated wrapper)
mod_path2 = 'sos_trades_core.sos_wrapping.test_discs.sos_Sobieski.SobieskiAerodynamics'

In [50]:
disc_name = 'SobieskiAerodynamics'
disc2_builder = ee.factory.get_builder_from_module(disc_name, mod_path2)
ee.factory.set_builders_to_coupling_builder(disc2_builder)

ee.configure() 

INFO:SoS.EE:configuring ...
INFO:SoS.EE.Coupling:The MDA solver of the Coupling MyStudy is set to MDAJacobi


In [51]:
ee.display_treeview_nodes()

INFO:SoS.EE:Nodes representation for Treeview MyStudy
|_ MyStudy
	|_ SobieskiAerodynamics


'Nodes representation for Treeview MyStudy\n|_ MyStudy\n\t|_ SobieskiAerodynamics'

In [52]:
my_disc2 = ee.root_process.sos_disciplines[0]

In [53]:
DESC_IN = my_disc2.DESC_IN
DESC_OUT = my_disc2.DESC_OUT
DESC_IN_df = pd.DataFrame.from_dict(DESC_IN,orient='index')
DESC_OUT_df = pd.DataFrame.from_dict(DESC_OUT,orient='index')

In [54]:
DESC_IN_df

type                                  default visibility  \
x_2   array                                    [1.0]     Shared   
y_12  array                       [50606.9742, 0.95]     Shared   
y_32  array                             [0.50279625]     Shared   
z     array  [0.05, 45000.0, 1.6, 5.5, 55.0, 1000.0]     Shared   

             namespace  
x_2   ns_OptimSobieski  
y_12  ns_OptimSobieski  
y_32  ns_OptimSobieski  
z     ns_OptimSobieski

In [55]:
DESC_OUT_df

type visibility         namespace
y_2   array     Shared  ns_OptimSobieski
y_21  array     Shared  ns_OptimSobieski
y_23  array     Shared  ns_OptimSobieski
y_24  array     Shared  ns_OptimSobieski
g_2   array     Shared  ns_OptimSobieski

#Provide inputs

In [56]:
priv_in_values = {
                  'MyStudy.x_2': [1.0],
                  'MyStudy.y_12':  [50606.9,0.95], 
                  'MyStudy.y_32': [12194.2], 
                  'MyStudy.z': [0.05,45000,1.6,5.5,55,1000]
                  }

In [57]:
priv_in_values

{'MyStudy.x_2': [1.0],
 'MyStudy.y_12': [50606.9, 0.95],
 'MyStudy.y_32': [12194.2],
 'MyStudy.z': [0.05, 45000, 1.6, 5.5, 55, 1000]}

In [58]:
ee.dm.set_values_from_dict(priv_in_values)
ee.root_process.update_from_dm()

In [59]:
print(ee.execute())

INFO:SoS.EE:PROCESS EXECUTION MyStudy STARTS...
INFO:SoS.EE:PROCESS EXECUTION MyStudy ENDS.


{'MyStudy.x_2': [1.0], 'MyStudy.y_12': [50606.9, 0.95], 'MyStudy.y_32': [12194.2], 'MyStudy.z': [0.05, 45000, 1.6, 5.5, 55, 1000], 'MyStudy.y_2': array([5.06069000e+04, 1.29535265e+04, 3.90680484e+00]), 'MyStudy.y_21': array([12953.52649046]), 'MyStudy.y_24': array([3.90680484]), 'MyStudy.g_2': array([-0.04])}


In [60]:
my_disc2.get_data_io_dict('out')['y_2']['value']

array([5.06069000e+04, 1.29535265e+04, 3.90680484e+00])

In [61]:
my_disc2.get_data_io_dict('out')['y_21']['value']

array([12953.52649046])

In [62]:
my_disc2.get_data_io_dict('out')['y_23']['value']

In [63]:
my_disc2.get_data_io_dict('out')['y_24']['value']

array([3.90680484])

In [64]:
my_disc2.get_data_io_dict('out')['g_2']['value']

array([-0.04])

In [65]:
my_disc2.compute_sos_jacobian()

In [66]:
#my_disc2.jac
pd.DataFrame(my_disc2.jac)

y_2  \
z     [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [165458.26978...   
x_2   [[0.0], [1518.2348699672957], [-0.457902127580...   
y_12  [[1.0, 0.0], [0.0007526771845305045, -25.90575...   
y_32                              [[0.0], [0.0], [0.0]]   

                                                  g_2  \
z     [[4.0000000000000036, 0.0, 0.0, 0.0, 0.0, 0.0]]   
x_2                                           [[0.0]]   
y_12                                     [[0.0, 0.0]]   
y_32                                          [[0.0]]   

                                  y_21  \
z     [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]   
x_2                            [[0.0]]   
y_12                      [[1.0, 0.0]]   
y_32                           [[0.0]]   

                                                   y_23  \
z     [[165458.26978767998, -0.6207344668522053, 161...   
x_2                              [[1518.2348699672957]]   
y_12     [[0.0007526771845305045, -25.905757693042016]]   
y_32                                            [[0.0]]   

                                                   y_24  
z     [[-49.90248561683625, 0.00018721453357221788, ...  
x_2                             [[-0.4579021275802293]]  
y_12    [[7.697204601896314e-05, 0.007813219020899815]]  
y_32                                            [[0.0]]

# 3) Set the discipline : here SobieskiPropulsion

In [67]:
ns_test = 'MyStudy'
ee = ExecutionEngine(ns_test)
ns_dict = {'ns_OptimSobieski': ns_test} # conform to shared variable x
ee.ns_manager.add_ns_def(ns_dict)

In [68]:
# Choice of the discipline (File that provides the wrapper and associated wrapper)
mod_path3 = 'sos_trades_core.sos_wrapping.test_discs.sos_Sobieski.SobieskiPropulsion'

In [69]:
disc_name = 'SobieskiPropulsion'
disc3_builder = ee.factory.get_builder_from_module(disc_name, mod_path3)
ee.factory.set_builders_to_coupling_builder(disc3_builder)

ee.configure() 

INFO:SoS.EE:configuring ...
INFO:SoS.EE.Coupling:The MDA solver of the Coupling MyStudy is set to MDAJacobi


In [70]:
ee.display_treeview_nodes()

INFO:SoS.EE:Nodes representation for Treeview MyStudy
|_ MyStudy
	|_ SobieskiPropulsion


'Nodes representation for Treeview MyStudy\n|_ MyStudy\n\t|_ SobieskiPropulsion'

In [71]:
my_disc3 = ee.root_process.sos_disciplines[0]

In [72]:
DESC_IN = my_disc3.DESC_IN
DESC_OUT = my_disc3.DESC_OUT
DESC_IN_df = pd.DataFrame.from_dict(DESC_IN,orient='index')
DESC_OUT_df = pd.DataFrame.from_dict(DESC_OUT,orient='index')

In [73]:
DESC_IN_df

type                                  default visibility  \
x_3   array                                    [0.5]     Shared   
y_23  array                         [12562.01206488]     Shared   
z     array  [0.05, 45000.0, 1.6, 5.5, 55.0, 1000.0]     Shared   

             namespace  
x_3   ns_OptimSobieski  
y_23  ns_OptimSobieski  
z     ns_OptimSobieski

In [74]:
DESC_OUT_df

type visibility         namespace
y_3   array     Shared  ns_OptimSobieski
y_34  array     Shared  ns_OptimSobieski
y_31  array     Shared  ns_OptimSobieski
y_32  array     Shared  ns_OptimSobieski
g_3   array     Shared  ns_OptimSobieski

#Provide inputs

In [75]:
priv_in_values = {
                  'MyStudy.x_3': [0.5],
                  'MyStudy.y_23':  [12194.2], 
                  'MyStudy.z': [0.05,45000,1.6,5.5,55,1000]
                  }

In [76]:
priv_in_values

{'MyStudy.x_3': [0.5],
 'MyStudy.y_23': [12194.2],
 'MyStudy.z': [0.05, 45000, 1.6, 5.5, 55, 1000]}

In [77]:
ee.dm.set_values_from_dict(priv_in_values)
ee.root_process.update_from_dm()

In [78]:
print(ee.execute())

INFO:SoS.EE:PROCESS EXECUTION MyStudy STARTS...
INFO:SoS.EE:PROCESS EXECUTION MyStudy ENDS.


{'MyStudy.x_3': [0.5], 'MyStudy.y_23': [12194.2], 'MyStudy.z': [0.05, 45000, 1.6, 5.5, 55, 1000], 'MyStudy.y_3': array([1.10754577e+00, 6.35428754e+03, 5.02793480e-01]), 'MyStudy.y_34': array([1.10754577]), 'MyStudy.y_31': array([6354.28754235]), 'MyStudy.y_32': array([0.50279348]), 'MyStudy.g_3': array([-0.99720652, -0.00279348,  0.16206032, -0.02      ])}


In [79]:
my_disc3.get_data_io_dict('out')['y_3']['value']

array([1.10754577e+00, 6.35428754e+03, 5.02793480e-01])

In [80]:
my_disc3.get_data_io_dict('out')['y_34']['value']

array([1.10754577])

In [81]:
my_disc3.get_data_io_dict('out')['y_31']['value']

array([6354.28754235])

In [82]:
my_disc3.get_data_io_dict('out')['y_32']['value']

array([0.50279348])

In [83]:
my_disc3.get_data_io_dict('out')['g_3']['value']

array([-0.99720652, -0.00279348,  0.16206032, -0.02      ])

In [84]:
my_disc3.compute_sos_jacobian()

In [85]:
#my_disc3.jac
pd.DataFrame(my_disc3.jac)

y_3  \
x_3   [[0.17541115841822139], [-13344.003838931347],...   
z     [[0.0, 3.224819119999993e-06, 0.04351374841045...   
y_23  [[0.0], [0.547145521597618], [4.12321825431185...   

                                                    g_3  \
x_3   [[-1.0055869607345926], [1.0055869607345926], ...   
z     [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [-0.0, -0.0, ...   
y_23  [[4.1232182543118555e-05], [-4.123218254311855...   

                                  y_31                              y_32  \
x_3            [[-13344.003838931347]]           [[-1.0055869607345926]]   
z     [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]   
y_23             [[0.547145521597618]]        [[4.1232182543118555e-05]]   

                                                   y_34  
x_3                             [[0.17541115841822139]]  
z     [[0.0, 3.224819119999993e-06, 0.04351374841045...  
y_23                                            [[0.0]]

# 4) Sobieski builder list

In [86]:
#from sos_trades_core.sos_wrapping.test_discs.sellar import Sellar1
from sos_trades_core.execution_engine.execution_engine import ExecutionEngine

In [87]:
ns_test = 'MyStudy'
ee = ExecutionEngine(ns_test)
ns_dict = {'ns_OptimSobieski': ns_test} # conform to shared variable x
ee.ns_manager.add_ns_def(ns_dict)

In [88]:
mod_path0 = 'sos_trades_core.sos_wrapping.test_discs.sos_Sobieski.SobieskiMission'
disc_name = 'SobieskiMission'
disc0_builder = ee.factory.get_builder_from_module(disc_name, mod_path0)

mod_path1 = 'sos_trades_core.sos_wrapping.test_discs.sos_Sobieski.SobieskiStructure'
disc_name = 'SobieskiStructure'
disc1_builder = ee.factory.get_builder_from_module(disc_name, mod_path1)

mod_path2 = 'sos_trades_core.sos_wrapping.test_discs.sos_Sobieski.SobieskiAerodynamics'
disc_name = 'SobieskiAerodynamics'
disc2_builder = ee.factory.get_builder_from_module(disc_name, mod_path2)

mod_path3 = 'sos_trades_core.sos_wrapping.test_discs.sos_Sobieski.SobieskiPropulsion'
disc_name = 'SobieskiPropulsion'
disc3_builder = ee.factory.get_builder_from_module(disc_name, mod_path3)

In [89]:
disc_list=[disc0_builder,disc1_builder,disc2_builder,disc2_builder]

In [90]:
coupling_builder = ee.factory.create_builder_coupling("SobieskyCoupling")
coupling_builder.set_builder_info('cls_builder', disc_list)
coupling_builder.set_builder_info('with_data_io', True)

In [91]:
#ee.factory.set_builders_to_coupling_builder([disc_list])
ee.factory.set_builders_to_coupling_builder([coupling_builder])

In [92]:
ee.configure() 

INFO:SoS.EE:configuring ...
INFO:SoS.EE.Coupling:The MDA solver of the Coupling MyStudy.SobieskyCoupling is set to MDAJacobi
INFO:SoS.EE.Coupling:The MDA solver of the Coupling MyStudy is set to MDAJacobi


In [93]:
ee.display_treeview_nodes()

INFO:SoS.EE:Nodes representation for Treeview MyStudy
|_ MyStudy
	|_ SobieskyCoupling
		|_ SobieskiStructure
		|_ SobieskiAerodynamics
		|_ SobieskiMission


'Nodes representation for Treeview MyStudy\n|_ MyStudy\n\t|_ SobieskyCoupling\n\t\t|_ SobieskiStructure\n\t\t|_ SobieskiAerodynamics\n\t\t|_ SobieskiMission'

In [94]:
priv_in_values = {
                  'MyStudy.z': [0.05,45000,1.6,5.5,55.,1000],
                  'MyStudy.y_14': [50606.9,7306.20],
                  'MyStudy.y_24':  [4.15], 
                  'MyStudy.y_34': [1.10], 
                  'MyStudy.x_1': [0.25,1.0],
                  'MyStudy.y_21':  [50606.9], 
                  'MyStudy.y_31': [6354.32], 
                  'MyStudy.x_2': [1.0],
                  'MyStudy.y_12':  [50606.9,0.95], 
                  'MyStudy.y_32': [12194.2], 
                  'MyStudy.x_3': [0.5],
                  'MyStudy.y_23':  [12194.2], 
                  }

In [95]:
#ee.dm.set_values_from_dict(priv_in_values)
#ee.root_process.update_from_dm()

In [96]:
ee.load_study_from_input_dict(priv_in_values)

INFO:SoS.EE:configuring ...
INFO:SoS.EE.Coupling:The MDA solver of the Coupling MyStudy.SobieskyCoupling is set to MDAJacobi
INFO:SoS.EE:configuring ...
INFO:SoS.EE.Coupling:The MDA solver of the Coupling MyStudy.SobieskyCoupling is set to MDAJacobi
INFO:SoS.EE:configuring ...
INFO:SoS.EE.Coupling:The MDA solver of the Coupling MyStudy is set to MDAJacobi


In [97]:
ee.display_treeview_nodes(True)

INFO:SoS.EE:Nodes representation for Treeview MyStudy
|_ MyStudy
	-> acceleration
	-> authorize_self_coupled_disciplines
	-> cache_file_path
	-> cache_type
	-> chain_linearize
	-> debug_mode
	-> epsilon0
	-> group_mda_disciplines
	-> linear_solver_MDA
	-> linear_solver_MDA_options
	-> linear_solver_MDA_preconditioner
	-> linear_solver_MDO
	-> linear_solver_MDO_options
	-> linear_solver_MDO_preconditioner
	-> linearization_mode
	-> max_mda_iter
	-> n_processes
	-> n_subcouplings_parallel
	-> relax_factor
	-> sub_mda_class
	-> tolerance
	-> tolerance_gs
	-> use_lu_fact
	-> warm_start
	-> warm_start_threshold
	-> x_1
	-> x_2
	-> y_12
	-> y_21
	-> y_31
	-> y_32
	-> y_34
	-> z
	<- g_1
	<- g_2
	<- residuals_history
	<- y_1
	<- y_11
	<- y_14
	<- y_2
	<- y_23
	<- y_24
	<- y_4
	|_ SobieskyCoupling
		-> acceleration
		-> authorize_self_coupled_disciplines
		-> cache_file_path
		-> cache_type
		-> chain_linearize
		-> debug_mode
		-> epsilon0
		-> group_mda_disciplines
		-> linear_solver_MDA
		->

'Nodes representation for Treeview MyStudy\n|_ MyStudy\n\t-> acceleration\n\t-> authorize_self_coupled_disciplines\n\t-> cache_file_path\n\t-> cache_type\n\t-> chain_linearize\n\t-> debug_mode\n\t-> epsilon0\n\t-> group_mda_disciplines\n\t-> linear_solver_MDA\n\t-> linear_solver_MDA_options\n\t-> linear_solver_MDA_preconditioner\n\t-> linear_solver_MDO\n\t-> linear_solver_MDO_options\n\t-> linear_solver_MDO_preconditioner\n\t-> linearization_mode\n\t-> max_mda_iter\n\t-> n_processes\n\t-> n_subcouplings_parallel\n\t-> relax_factor\n\t-> sub_mda_class\n\t-> tolerance\n\t-> tolerance_gs\n\t-> use_lu_fact\n\t-> warm_start\n\t-> warm_start_threshold\n\t-> x_1\n\t-> x_2\n\t-> y_12\n\t-> y_21\n\t-> y_31\n\t-> y_32\n\t-> y_34\n\t-> z\n\t<- g_1\n\t<- g_2\n\t<- residuals_history\n\t<- y_1\n\t<- y_11\n\t<- y_14\n\t<- y_2\n\t<- y_23\n\t<- y_24\n\t<- y_4\n\t|_ SobieskyCoupling\n\t\t-> acceleration\n\t\t-> authorize_self_coupled_disciplines\n\t\t-> cache_file_path\n\t\t-> cache_type\n\t\t-> chain_l

In [98]:
print(ee.execute())

INFO:SoS.EE:PROCESS EXECUTION MyStudy STARTS...
INFO:SoS.EE.Coupling:MyStudy.SobieskyCoupling MDA history
INFO:SoS.EE.Coupling:	It.	Res. norm
INFO:gemseo.mda.mda:	1	2.173919e+10
INFO:gemseo.mda.mda:	2	3.668539e+09
INFO:gemseo.mda.mda:	3	1.016098e+08
INFO:gemseo.mda.mda:	4	1.860735e+05
INFO:gemseo.mda.mda:	5	1.768542e+01
INFO:gemseo.mda.mda:	6	4.916882e-04
INFO:gemseo.mda.mda:	7	4.200776e-06
INFO:gemseo.mda.mda:	8	0.000000e+00
INFO:SoS.EE:PROCESS EXECUTION MyStudy ENDS.


{'MyStudy.x_1': [0.25, 1.0], 'MyStudy.y_21': array([12949.0434832]), 'MyStudy.y_31': [6354.32], 'MyStudy.z': [0.05, 45000, 1.6, 5.5, 55.0, 1000], 'MyStudy.x_2': [1.0], 'MyStudy.y_12': array([4.42517865e+04, 9.50000000e-01]), 'MyStudy.y_32': [12194.2], 'MyStudy.y_34': [1.1], 'MyStudy.y_1': array([4.42517865e+04, 7.30620262e+03, 9.50000000e-01]), 'MyStudy.y_11': array([0.18044962]), 'MyStudy.y_14': array([44251.78645414,  7306.20262124]), 'MyStudy.g_1': array([ 0.035     , -0.00666667, -0.0275    , -0.04      , -0.04833333,
       -0.09      , -0.15      ]), 'MyStudy.y_2': array([4.42517865e+04, 1.29490435e+04, 3.41737878e+00]), 'MyStudy.y_24': array([3.41737878]), 'MyStudy.g_2': array([-0.04]), 'MyStudy.y_4': array([514.11217526])}
